package br.com.opa.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import br.com.opa.enums.StatusOfertaEnum;
import br.com.opa.enums.TipoOfertaEnum;

/**
 * Oferta generated by hbm2java
 */

@Entity
@Table(name = "opa_oferta")
public class Oferta implements java.io.Serializable {

	private static final long serialVersionUID = -2661170974189846764L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="SEQ_OFERTA", sequenceName="OPA_SEQ_O")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_OFERTA")
	private int id;
	
	@Column(name = "nome", nullable = false, length = 100)
	private String nome;
	
	@Column(name = "codigo", nullable = false)
	private int codigo;
	
	@Column(name = "descricao", nullable = false, length = 400)
	private String descricao;
	
	@Enumerated(EnumType.STRING)
	@Column(name = "tipo", nullable = false, length = 50)
	private TipoOfertaEnum tipo;
	
	@Column(name = "url_padrao", nullable = false, length = 400)
	private String urlPadrao;
	
	@Column(name = "preco", nullable = false)
	private long preco;
		
	@Enumerated(EnumType.STRING)
	@Column(name = "status", nullable = false, length = 50)
	private StatusOfertaEnum status;
	
	@Column(name = "data_limite", nullable = false, length = 50)
	private String dataLimite;
		
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_cadastro", nullable = false)
	private Date dataCadastro;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao")
	private Date dataAlteracao;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exclusao")
	private Date dataExclusao;
	
	/*@OneToOne(fetch=FetchType.LAZY, mappedBy="usuario")
	private Usuario usuario;*/
	
	@Column(name = "id_usuario", nullable = false)
	private int idUsuario;
	
	@Column(name = "id_categoria", nullable = false)
	private int idCategoria;

	@Transient
	private boolean acessoPublico;

	public Oferta() {
	}
	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	
	public Date getDataExclusao() {
		return dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	public Date getDataCadastro() {
		return dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public Date getDataAlteracao() {
		return dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}
	
	public StatusOfertaEnum getStatus() {
		return status;
	}

	public void setStatus(StatusOfertaEnum status) {
		this.status = status;
	}
	
	public TipoOfertaEnum getTipo() {
		return tipo;
	}

	public void setTipo(TipoOfertaEnum tipo) {
		this.tipo = tipo;
	}
	
	public boolean isAcessoPublico() {
		return acessoPublico;
	}

	public void setAcessoPublico(boolean acessoPublico) {
		this.acessoPublico = acessoPublico;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getUrlPadrao() {
		return urlPadrao;
	}

	public void setUrlPadrao(String urlPadrao) {
		this.urlPadrao = urlPadrao;
	}

	public long getPreco() {
		return preco;
	}

	public void setPreco(long preco) {
		this.preco = preco;
	}

	public String getDataLimite() {
		return dataLimite;
	}

	public void setDataLimite(String dataLimite) {
		this.dataLimite = dataLimite;
	}

	public int getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdCategoria() {
		return idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

}
